---
name: Reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "haradev"
          replace: "rudradev"
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
         name: my-artifact
